base_config:
  - configs/acoustic.yaml

datasets:
  - name: emvd
    raw_data_dir: data/emvd/ds_output
    speaker: emvd
    language: en
    spk_id: 0
    test_prefixes:
      - Singer1_ClearVoice_High_a
      - Singer1_DeathGrowl_Low_a
      - Singer10_ClearVoice_High_a
      - Singer10_DeathGrowl_Low_a

speakers:
  - emvd

dictionaries:
  en: dictionaries/arpabet.txt

pe: parselmouth
pe_ckpt: ~

raw_data_dir:    data/emvd/ds_output
binary_data_dir: data/emvd/binary

num_spk: 27
use_spk_id: true
use_growl_embed: true

max_frames: 2000
lr: 0.0004
max_updates: 50000
val_check_interval: 2000